CHARACTER_LIST = [
    {"name": "Ryu", "slug": "ryu"},
    {"name": "Luke", "slug": "luke"},
    {"name": "Jamie", "slug": "jamie"},
    {"name": "Chun-Li", "slug": "chunli"},
    {"name": "Guile", "slug": "guile"},
    {"name": "Kimberly", "slug": "kimberly"},
    {"name": "Juri", "slug": "juri"},
    {"name": "Ken", "slug": "ken"},
    {"name": "Blanka", "slug": "blanka"},
    {"name": "Dhalsim", "slug": "dhalsim"},
    {"name": "E.Honda", "slug": "honda"},
    {"name": "Dee Jay", "slug": "deejay"},
    {"name": "Manon", "slug": "manon"},
    {"name": "Marisa", "slug": "marisa"},
    {"name": "JP", "slug": "jp"},
    {"name": "Zangief", "slug": "zangief"},
    {"name": "Lily", "slug": "lily"},
    {"name": "Cammy", "slug": "cammy"},
    {"name": "Rashid", "slug": "rashid"},
    {"name": "A.K.I.", "slug": "aki"},
    {"name": "Ed", "slug": "ed"},
    {"name": "Akuma", "slug": "gouki"},
    {"name": "M.Bison", "slug": "mbison"},
    {"name": "Terry", "slug": "terry"},
    {"name": "Mai", "slug": "mai"},
    {"name": "Elena", "slug": "elena"},
    {"name": "C.Viper", "slug": "cviper"},
    {"name": "Sagat", "slug": "sagat"},
    {"name": "Alex", "slug": "alex"},
    # {"name": "Ingrid", "slug": "ingrid"},  # 未リリース（2026年春後半予定）
]
